### PR TITLE
updated template apiVersion for test resources to be fully qualified

### PR DESCRIPTION
**Pull request by garethahealy**
#### What is this PR About?
minor fix to fully qualify the template resources

cc: @redhat-cop/rego-policies

### CODE REVIEW

**Comment by springdo** [comment]
@garethahealy - looks like your build is failing for a timeout issue. I guess you can rerun the action? or push an empty commit to the pr to trigger it again if you like

**Comment by garethahealy** [comment]
rebased to pull in KinD version bump

**Pull request merged**
