### PR TITLE
Regenerated docs

### PR DESCRIPTION
**Pull request by garethahealy**
#### What is this PR About?
New version of konstraint so docs code their side has been tweaked.

#### Check list
- [x] Have you re-generated `POLICIES.md`

cc: @redhat-cop/rego-policies

### CODE REVIEW

**Comment by springdo** [comment]
is there really just some white space changes here?

**Comment by garethahealy** [comment]
@springdo yep; since its an auto-generated file, when they change how their code works it makes slight changes on our doc.

**Review by pabrahamsson — APPROVED** [review]
/approve

**Pull request merged**
