### PR TITLE
Fixed docs not being upto date

### PR DESCRIPTION
**Pull request by garethahealy**
#### What is this PR About?
Updated docs due to konstraint changes

Fixes: https://github.com/redhat-cop/rego-policies/issues/89

#### How do we test this?
All actions green.

cc: @redhat-cop/rego-policies

### CODE REVIEW

**Comment by garethahealy** [comment]
**DONT MERGE** : Needs a few other changes, but just raised to check action goes green.

**Comment by garethahealy** [comment]
@ckavili ; Ready for review, but don't merge yet as konstraint has an open PR which will slightly change the generated docs.

**Comment by garethahealy** [comment]
need to fix some of the anchors, as they are deadlines due to containing `.` or `'`

**Comment by garethahealy** [comment]
@ckavili ; ready for review/merge.

**Comment by ckavili** [comment]
Love this version of `POLICIES.md` 👍 

/lgtm

**Pull request merged**
