### PR TITLE
Converted policies to gatekeeper naming/structure

### PR DESCRIPTION
**Pull request by garethahealy**
#### What is this PR About?
Converted 1 policy to follow the gatekeeper/konstraint format.
- https://github.com/redhat-cop/rego-policies/issues/67

#### How do we test this?
ACTION!

cc: @redhat-cop/rego-policies

### CODE REVIEW

**Comment by garethahealy** [comment]
**DONT MERGE**

**Comment by garethahealy** [comment]
FYI:

The below are generated by `konstraint create`
- constraint.yaml
- template.yaml

The below are generated by `konstraint doc -o POLICIES.md`
- POLICIES.md

`policy/lib/konstraint.rego` is pulled via:
-  conftest pull https://raw.githubusercontent.com/plexsystems/konstraint/main/examples/lib/kubernetes.rego

**Comment by garethahealy** [comment]
@ckavili / @springdo ; if you want to have a play with this PR:

1. git clone it
2. `rm -rf /tmp/rhcop; _test/conftest-unittests.sh` ; run the conftests
3. `_test/deploy_gatekeeper.sh` ; deploy gatekeeper to a OCP4 cluster - expects to be logged in - use RHPDS or something that you don't mind breaking - a bad rego can cause all the things to break. NOTE: this script needs improving, see the todos/sleeps. if you get a JSON output of errors, keep running that command until they disappear and then copy+paste the steps afterwards
4. `_test/gatekeeper-integrationtests.sh` ; run the tests against gatekeeper

any issues, ping me on gchat.

**Comment by garethahealy** [comment]
@springdo @ckavili ; ready for review/merge. it's a big boy this PR, but not sure how else to split this out since the rego files have gone from 10 to 50.

**Comment by ckavili** [comment]
Awesome!! 🙌🏻 I'll get a cluster and play with it right away 🚴🏻

**Comment by ckavili** [comment]
I had to reinstall yq with `pip install yq` because the one comes with `brew install` doesn't have options like `--yaml-output` 🤷  Other than that, it looks really good to me 💃🏻

**Comment by garethahealy** [comment]
@ckavili ; yep, sadly there are two yq binaries in the wild. 
- the brew one (https://github.com/mikefarah/yq) which uses its own syntax to update yaml
- the pip one (https://github.com/kislyuk/yq) which is a wrapper around jq.

I prefer the wrapper one, as it means i don't need to learn another syntax, if I can 'JQ it' i can 'YQ it'.

I'll add an extra check here to make sure its the correct yq:
- https://github.com/redhat-cop/bats-library/blob/master/load.bash#L3

**Comment by garethahealy** [comment]
Added yq check: https://github.com/redhat-cop/bats-library/pull/17

**Comment by springdo** [comment]
@ckavili you're good with this PR right?

**Pull request merged**
