### PR TITLE
Updating naming of policies to follow a format

### PR DESCRIPTION
**Pull request by garethahealy**
#### What is this PR About?
Adds a naming format to follow. Hopefully, should be flexible and make it easier to understand what the policies do.

#### How do we test this?
See action output still green

cc: @redhat-cop/rego-policies

### CODE REVIEW

**Comment by springdo** [comment]
Happy to merge this in, but does it make more sense for us to use a folder for each ie `warn`, `deny` and `allow`? 

I guess if it grows to that many we could look at this but for now this /lgtm

**Comment by springdo** [comment]
`/lgtm`

**Comment by garethahealy** [comment]
@springdo ; yeah, happy to review as we grow the policies.

**Comment by springdo** [comment]
cool - let's come back to it then if we need

**Pull request merged**
