### PR TITLE
Added OCP 4.2 and 4.3 deprecated api versions

### PR DESCRIPTION
**Pull request by garethahealy**
#### What is this PR About?
Some base policies for 4.2/4.3 

cc: @redhat-cop/day-in-the-life

### CODE REVIEW

**Comment by garethahealy** [comment]
@tylerauerbeck ; what did you have in mind?

for these, am not sure what I can say, other than what is already said in the rego file. which if you look at the rego file, its obvious that's what is being checked... feels like I'd doc'ing the code, when its easier to just read the code, if that makes sense.

The only thing I could think would be:

> The following apiVersions are deprecated:
> - servicecatalog.k8s.io/v1beta1
> - automationbroker.io/v1alpha1
> - osb.openshift.io/v1 
> - operatorsources.operators.coreos.com/v1 
> - catalogsourceconfigs.operators.coreos.com/v1 
> - catalogsourceconfigs.operators.coreos.com/v2

**Comment by garethahealy** [comment]
@tylerauerbeck ; pushed a change to readme. that look ok?

**Comment by garethahealy** [comment]
Just ran a quick test using helm:
`MacBook-Pro:rego-policies garethhealy$ helm template --dependency-update redhat-consulting-uk-helm3/app-of-apps --values /Users/garethhealy/Documents/github/RedHat-Consulting-UK/future-cicd-app/my-project-app.yaml | conftest test -
FAIL - Application/basic-sprint-boot: I dont like argo!
FAIL - Application/generic-java-buildconfig: I dont like argo!`

my policy
`package main

deny[msg] {
  input.apiVersion == "argoproj.io/v1alpha1"
  input.kind == "Application"
  msg := sprintf("%s/%s: I dont like argo!", [input.kind, input.metadata.name])
}`

**Comment by pabrahamsson** [comment]
@garethahealy in my example chart I have a rolebinding that has a deprecated `apiVersion`
```
apiVersion: v1
kind: RoleBinding
metadata:
...
```
When I test this against the deprecated 4.3 rules I would expect it to fail, but
```
helm template . | conftest test - -p /tmp/43.rego

6 tests, 6 passed, 0 warnings, 0 failures
```
Are you able to verify? Or am I missing something?

**Comment by garethahealy** [comment]
Added catch all method after chats with @pabrahamsson blocks which are not in a list or template are not dropping through into the _deny methods - they do in OPA.

**Comment by pabrahamsson** [comment]
@tylerauerbeck are you good with the updated README?

**Pull request merged**
